apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cks-prep-cluster
  region: us-east-1
  version: "1.33"

iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    amiFamily: Bottlerocket
    bottlerocket:
      enableAdminContainer: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: metrics-server
    version: latest
