apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cks-prep-cluster
  region: us-east-1
  version: "1.33"

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 4

